System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "stage": 0,
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "/cdn/react1-todoapp/jspm_packages/github/*",
    "npm:*": "/cdn/react1-todoapp/jspm_packages/npm/*"
  },
  bundles: {
    "deps-bundle.js": [
      "npm:axios@0.9.1",
      "npm:axios@0.9.1/index",
      "npm:axios@0.9.1/lib/axios",
      "npm:axios@0.9.1/lib/utils",
      "npm:axios@0.9.1/lib/helpers/isAbsoluteURL",
      "npm:axios@0.9.1/lib/helpers/combineURLs",
      "npm:axios@0.9.1/lib/helpers/bind",
      "npm:axios@0.9.1/lib/core/InterceptorManager",
      "npm:axios@0.9.1/lib/core/dispatchRequest",
      "npm:axios@0.9.1/lib/defaults",
      "github:jspm/nodelibs-process@0.1.2",
      "github:jspm/nodelibs-process@0.1.2/index",
      "npm:process@0.11.2",
      "npm:process@0.11.2/browser",
      "npm:axios@0.9.1/lib/helpers/spread",
      "npm:axios@0.9.1/lib/helpers/transformData",
      "npm:axios@0.9.1/lib/adapters/xhr",
      "npm:axios@0.9.1/lib/helpers/buildURL",
      "npm:axios@0.9.1/lib/helpers/parseHeaders",
      "npm:axios@0.9.1/lib/helpers/btoa",
      "npm:axios@0.9.1/lib/helpers/isURLSameOrigin",
      "npm:axios@0.9.1/lib/helpers/cookies",
      "npm:redux-thunk@1.0.3",
      "npm:redux-thunk@1.0.3/lib/index",
      "npm:redux-devtools-log-monitor@1.0.4",
      "npm:redux-devtools-log-monitor@1.0.4/lib/index",
      "npm:redux-devtools-log-monitor@1.0.4/lib/LogMonitor",
      "npm:react@0.14.7",
      "npm:redux-devtools@3.1.0",
      "npm:react@0.14.7/react",
      "npm:redux-devtools@3.1.0/lib/index",
      "npm:react@0.14.7/lib/React",
      "npm:redux-devtools@3.1.0/lib/instrument",
      "npm:redux-devtools@3.1.0/lib/persistState",
      "npm:redux-devtools@3.1.0/lib/createDevTools",
      "npm:react@0.14.7/lib/ReactDOM",
      "npm:react@0.14.7/lib/ReactDOMServer",
      "npm:react@0.14.7/lib/ReactIsomorphic",
      "npm:react@0.14.7/lib/Object.assign",
      "npm:react@0.14.7/lib/deprecated",
      "npm:lodash@4.2.1/difference",
      "npm:lodash@4.2.1/mapValues",
      "npm:lodash@4.2.1/identity",
      "npm:react-redux@4.4.0",
      "npm:react@0.14.7/lib/ReactCurrentOwner",
      "npm:react@0.14.7/lib/ReactDOMTextComponent",
      "npm:react@0.14.7/lib/ReactDefaultInjection",
      "npm:react@0.14.7/lib/ReactInstanceHandles",
      "npm:react@0.14.7/lib/ReactMount",
      "npm:react@0.14.7/lib/ReactPerf",
      "npm:react@0.14.7/lib/ReactReconciler",
      "npm:react@0.14.7/lib/ReactUpdates",
      "npm:react@0.14.7/lib/ReactVersion",
      "npm:react@0.14.7/lib/findDOMNode",
      "npm:react@0.14.7/lib/renderSubtreeIntoContainer",
      "npm:fbjs@0.6.1/lib/warning",
      "npm:fbjs@0.6.1/lib/ExecutionEnvironment",
      "npm:react@0.14.7/lib/ReactServerRendering",
      "npm:react@0.14.7/lib/ReactChildren",
      "npm:react@0.14.7/lib/ReactComponent",
      "npm:react@0.14.7/lib/ReactClass",
      "npm:react@0.14.7/lib/ReactDOMFactories",
      "npm:react@0.14.7/lib/ReactElement",
      "npm:react@0.14.7/lib/ReactElementValidator",
      "npm:react@0.14.7/lib/ReactPropTypes",
      "npm:react@0.14.7/lib/onlyChild",
      "npm:lodash@4.2.1/_baseDifference",
      "npm:lodash@4.2.1/_baseFlatten",
      "npm:lodash@4.2.1/isArrayLikeObject",
      "npm:lodash@4.2.1/rest",
      "npm:lodash@4.2.1/_baseForOwn",
      "npm:lodash@4.2.1/_baseIteratee",
      "npm:react-redux@4.4.0/lib/index",
      "npm:react@0.14.7/lib/DOMChildrenOperations",
      "npm:react@0.14.7/lib/DOMPropertyOperations",
      "npm:react@0.14.7/lib/ReactComponentBrowserEnvironment",
      "npm:react@0.14.7/lib/escapeTextContentForBrowser",
      "npm:react@0.14.7/lib/setTextContent",
      "npm:react@0.14.7/lib/validateDOMNesting",
      "npm:react@0.14.7/lib/BeforeInputEventPlugin",
      "npm:react@0.14.7/lib/ChangeEventPlugin",
      "npm:react@0.14.7/lib/ClientReactRootIndex",
      "npm:react@0.14.7/lib/DefaultEventPluginOrder",
      "npm:react@0.14.7/lib/EnterLeaveEventPlugin",
      "npm:react@0.14.7/lib/HTMLDOMPropertyConfig",
      "npm:react@0.14.7/lib/ReactBrowserComponentMixin",
      "npm:react@0.14.7/lib/ReactDefaultBatchingStrategy",
      "npm:react@0.14.7/lib/ReactDOMComponent",
      "npm:react@0.14.7/lib/ReactEventListener",
      "npm:react@0.14.7/lib/ReactInjection",
      "npm:react@0.14.7/lib/ReactReconcileTransaction",
      "npm:react@0.14.7/lib/SelectEventPlugin",
      "npm:react@0.14.7/lib/ServerReactRootIndex",
      "npm:react@0.14.7/lib/SimpleEventPlugin",
      "npm:react@0.14.7/lib/SVGDOMPropertyConfig",
      "npm:react@0.14.7/lib/ReactDefaultPerf",
      "npm:react@0.14.7/lib/ReactRootIndex",
      "npm:fbjs@0.6.1/lib/invariant",
      "npm:react@0.14.7/lib/DOMProperty",
      "npm:react@0.14.7/lib/ReactBrowserEventEmitter",
      "npm:react@0.14.7/lib/ReactDOMFeatureFlags",
      "npm:react@0.14.7/lib/ReactEmptyComponentRegistry",
      "npm:react@0.14.7/lib/ReactInstanceMap",
      "npm:react@0.14.7/lib/ReactMarkupChecksum",
      "npm:react@0.14.7/lib/ReactUpdateQueue",
      "npm:fbjs@0.6.1/lib/emptyObject",
      "npm:fbjs@0.6.1/lib/containsNode",
      "npm:react@0.14.7/lib/instantiateReactComponent",
      "npm:react@0.14.7/lib/setInnerHTML",
      "npm:react@0.14.7/lib/shouldUpdateReactComponent",
      "npm:react@0.14.7/lib/ReactRef",
      "npm:react@0.14.7/lib/CallbackQueue",
      "npm:react@0.14.7/lib/PooledClass",
      "npm:react@0.14.7/lib/Transaction",
      "npm:fbjs@0.6.1/lib/emptyFunction",
      "npm:react@0.14.7/lib/ReactServerBatchingStrategy",
      "npm:react@0.14.7/lib/ReactServerRenderingTransaction",
      "npm:react@0.14.7/lib/traverseAllChildren",
      "npm:react@0.14.7/lib/ReactNoopUpdateQueue",
      "npm:react@0.14.7/lib/canDefineProperty",
      "npm:react@0.14.7/lib/ReactPropTypeLocations",
      "npm:react@0.14.7/lib/ReactPropTypeLocationNames",
      "npm:fbjs@0.6.1/lib/keyMirror",
      "npm:fbjs@0.6.1/lib/keyOf",
      "npm:fbjs@0.6.1/lib/mapObject",
      "npm:react@0.14.7/lib/getIteratorFn",
      "npm:lodash@4.2.1/_SetCache",
      "npm:lodash@4.2.1/_arrayIncludes",
      "npm:lodash@4.2.1/_arrayIncludesWith",
      "npm:lodash@4.2.1/_arrayMap",
      "npm:lodash@4.2.1/_baseUnary",
      "npm:lodash@4.2.1/_cacheHas",
      "npm:lodash@4.2.1/_arrayPush",
      "npm:lodash@4.2.1/isArguments",
      "npm:lodash@4.2.1/isArray",
      "npm:lodash@4.2.1/isArrayLike",
      "npm:lodash@4.2.1/isObjectLike",
      "npm:lodash@4.2.1/_apply",
      "npm:lodash@4.2.1/toInteger",
      "npm:lodash@4.2.1/_baseFor",
      "npm:lodash@4.2.1/keys",
      "npm:lodash@4.2.1/_baseMatches",
      "npm:lodash@4.2.1/_baseMatchesProperty",
      "npm:lodash@4.2.1/property",
      "npm:react-redux@4.4.0/lib/components/Provider",
      "npm:react-redux@4.4.0/lib/components/connect",
      "npm:react@0.14.7/lib/Danger",
      "npm:react@0.14.7/lib/ReactMultiChildUpdateTypes",
      "npm:react@0.14.7/lib/quoteAttributeValueForBrowser",
      "npm:react@0.14.7/lib/ReactDOMIDOperations",
      "npm:react@0.14.7/lib/EventConstants",
      "npm:react@0.14.7/lib/EventPropagators",
      "npm:react@0.14.7/lib/FallbackCompositionState",
      "npm:react@0.14.7/lib/SyntheticCompositionEvent",
      "npm:react@0.14.7/lib/SyntheticInputEvent",
      "npm:react@0.14.7/lib/EventPluginHub",
      "npm:react@0.14.7/lib/SyntheticEvent",
      "npm:react@0.14.7/lib/getEventTarget",
      "npm:react@0.14.7/lib/isEventSupported",
      "npm:react@0.14.7/lib/isTextInputElement",
      "npm:react@0.14.7/lib/SyntheticMouseEvent",
      "npm:react@0.14.7/lib/AutoFocusUtils",
      "npm:react@0.14.7/lib/CSSPropertyOperations",
      "npm:react@0.14.7/lib/ReactDOMButton",
      "npm:react@0.14.7/lib/ReactDOMInput",
      "npm:react@0.14.7/lib/ReactDOMOption",
      "npm:react@0.14.7/lib/ReactDOMSelect",
      "npm:react@0.14.7/lib/ReactDOMTextarea",
      "npm:react@0.14.7/lib/ReactMultiChild",
      "npm:fbjs@0.6.1/lib/shallowEqual",
      "npm:fbjs@0.6.1/lib/EventListener",
      "npm:fbjs@0.6.1/lib/getUnboundedScrollPosition",
      "npm:react@0.14.7/lib/ReactComponentEnvironment",
      "npm:react@0.14.7/lib/ReactEmptyComponent",
      "npm:react@0.14.7/lib/ReactNativeComponent",
      "npm:react@0.14.7/lib/ReactInputSelection",
      "npm:fbjs@0.6.1/lib/getActiveElement",
      "npm:react@0.14.7/lib/SyntheticClipboardEvent",
      "npm:react@0.14.7/lib/SyntheticFocusEvent",
      "npm:react@0.14.7/lib/SyntheticKeyboardEvent",
      "npm:react@0.14.7/lib/SyntheticDragEvent",
      "npm:react@0.14.7/lib/SyntheticTouchEvent",
      "npm:react@0.14.7/lib/SyntheticUIEvent",
      "npm:react@0.14.7/lib/SyntheticWheelEvent",
      "npm:react@0.14.7/lib/getEventCharCode",
      "npm:react@0.14.7/lib/ReactDefaultPerfAnalysis",
      "npm:fbjs@0.6.1/lib/performanceNow",
      "npm:react@0.14.7/lib/EventPluginRegistry",
      "npm:react@0.14.7/lib/ReactEventEmitterMixin",
      "npm:react@0.14.7/lib/ViewportMetrics",
      "npm:react@0.14.7/lib/adler32",
      "npm:fbjs@0.6.1/lib/isTextNode",
      "npm:react@0.14.7/lib/ReactCompositeComponent",
      "npm:react@0.14.7/lib/ReactOwner",
      "npm:lodash@4.2.1/_MapCache",
      "npm:lodash@4.2.1/_cachePush",
      "npm:lodash@4.2.1/_baseIndexOf",
      "npm:lodash@4.2.1/_isKeyable",
      "npm:lodash@4.2.1/_getLength",
      "npm:lodash@4.2.1/isFunction",
      "npm:lodash@4.2.1/isLength",
      "npm:lodash@4.2.1/toNumber",
      "npm:lodash@4.2.1/_createBaseFor",
      "npm:lodash@4.2.1/_baseHas",
      "npm:lodash@4.2.1/_baseKeys",
      "npm:lodash@4.2.1/_indexKeys",
      "npm:lodash@4.2.1/_isIndex",
      "npm:lodash@4.2.1/_isPrototype",
      "npm:lodash@4.2.1/_baseIsMatch",
      "npm:lodash@4.2.1/_getMatchData",
      "npm:lodash@4.2.1/_baseIsEqual",
      "npm:lodash@4.2.1/get",
      "npm:lodash@4.2.1/hasIn",
      "npm:lodash@4.2.1/_baseProperty",
      "npm:lodash@4.2.1/_basePropertyDeep",
      "npm:lodash@4.2.1/_isKey",
      "npm:react-redux@4.4.0/lib/utils/storeShape",
      "npm:react-redux@4.4.0/lib/utils/shallowEqual",
      "npm:react-redux@4.4.0/lib/utils/wrapActionCreators",
      "npm:lodash@4.2.1/isPlainObject",
      "npm:hoist-non-react-statics@1.0.5",
      "npm:invariant@2.2.0",
      "npm:fbjs@0.6.1/lib/createNodesFromMarkup",
      "npm:fbjs@0.6.1/lib/getMarkupWrap",
      "npm:react@0.14.7/lib/accumulateInto",
      "npm:react@0.14.7/lib/forEachAccumulated",
      "npm:react@0.14.7/lib/getTextContentAccessor",
      "npm:react@0.14.7/lib/EventPluginUtils",
      "npm:react@0.14.7/lib/ReactErrorUtils",
      "npm:react@0.14.7/lib/getEventModifierState",
      "npm:fbjs@0.6.1/lib/focusNode",
      "npm:react@0.14.7/lib/CSSProperty",
      "npm:fbjs@0.6.1/lib/camelizeStyleName",
      "npm:react@0.14.7/lib/dangerousStyleValue",
      "npm:fbjs@0.6.1/lib/hyphenateStyleName",
      "npm:fbjs@0.6.1/lib/memoizeStringOnly",
      "npm:react@0.14.7/lib/LinkedValueUtils",
      "npm:react@0.14.7/lib/ReactChildReconciler",
      "npm:react@0.14.7/lib/flattenChildren",
      "npm:react@0.14.7/lib/ReactDOMSelection",
      "npm:react@0.14.7/lib/getEventKey",
      "npm:fbjs@0.6.1/lib/performance",
      "npm:fbjs@0.6.1/lib/isNode",
      "npm:lodash@4.2.1/_mapClear",
      "npm:lodash@4.2.1/_mapDelete",
      "npm:lodash@4.2.1/_mapGet",
      "npm:lodash@4.2.1/_mapHas",
      "npm:lodash@4.2.1/_mapSet",
      "npm:lodash@4.2.1/_indexOfNaN",
      "npm:lodash@4.2.1/isObject",
      "npm:lodash@4.2.1/_baseTimes",
      "npm:lodash@4.2.1/isString",
      "npm:lodash@4.2.1/_Stack",
      "npm:lodash@4.2.1/_isStrictComparable",
      "npm:lodash@4.2.1/toPairs",
      "npm:lodash@4.2.1/_baseIsEqualDeep",
      "npm:lodash@4.2.1/_baseGet",
      "npm:lodash@4.2.1/_baseHasIn",
      "npm:lodash@4.2.1/_hasPath",
      "npm:redux@3.3.0",
      "npm:lodash@4.2.1/_isHostObject",
      "npm:hoist-non-react-statics@1.0.5/index",
      "npm:invariant@2.2.0/browser",
      "npm:fbjs@0.6.1/lib/createArrayFromMixed",
      "npm:fbjs@0.6.1/lib/camelize",
      "npm:fbjs@0.6.1/lib/hyphenate",
      "npm:react@0.14.7/lib/getNodeForCharacterOffset",
      "npm:lodash@4.2.1/_Hash",
      "npm:lodash@4.2.1/_Map",
      "npm:lodash@4.2.1/_assocDelete",
      "npm:lodash@4.2.1/_hashDelete",
      "npm:lodash@4.2.1/_assocGet",
      "npm:lodash@4.2.1/_hashGet",
      "npm:lodash@4.2.1/_assocHas",
      "npm:lodash@4.2.1/_hashHas",
      "npm:lodash@4.2.1/_assocSet",
      "npm:lodash@4.2.1/_hashSet",
      "npm:lodash@4.2.1/_stackClear",
      "npm:lodash@4.2.1/_stackDelete",
      "npm:lodash@4.2.1/_stackGet",
      "npm:lodash@4.2.1/_stackHas",
      "npm:lodash@4.2.1/_stackSet",
      "npm:lodash@4.2.1/_baseToPairs",
      "npm:lodash@4.2.1/_equalArrays",
      "npm:lodash@4.2.1/_equalByTag",
      "npm:lodash@4.2.1/_equalObjects",
      "npm:lodash@4.2.1/_getTag",
      "npm:lodash@4.2.1/isTypedArray",
      "npm:lodash@4.2.1/_baseToPath",
      "npm:lodash@4.2.1/last",
      "npm:lodash@4.2.1/_parent",
      "npm:redux@3.3.0/lib/index",
      "npm:fbjs@0.6.1/lib/toArray",
      "npm:lodash@4.2.1/_nativeCreate",
      "npm:lodash@4.2.1/_getNative",
      "npm:lodash@4.2.1/_root",
      "npm:lodash@4.2.1/_assocIndexOf",
      "npm:lodash@4.2.1/_arraySome",
      "npm:lodash@4.2.1/_Symbol",
      "npm:lodash@4.2.1/_Uint8Array",
      "npm:lodash@4.2.1/_mapToArray",
      "npm:lodash@4.2.1/_setToArray",
      "npm:lodash@4.2.1/_Set",
      "npm:lodash@4.2.1/_stringToPath",
      "npm:lodash@4.2.1/_baseSlice",
      "npm:redux@3.3.0/lib/createStore",
      "npm:redux@3.3.0/lib/combineReducers",
      "npm:redux@3.3.0/lib/bindActionCreators",
      "npm:redux@3.3.0/lib/applyMiddleware",
      "npm:redux@3.3.0/lib/compose",
      "npm:redux@3.3.0/lib/utils/warning",
      "npm:lodash@4.2.1/isNative",
      "npm:lodash@4.2.1/_checkGlobal",
      "npm:lodash@4.2.1/eq",
      "npm:lodash@4.2.1/toString",
      "npm:lodash@4.2.1/isSymbol",
      "npm:redux-devtools-log-monitor@1.0.4/lib/actions",
      "npm:react-pure-render@1.0.2/function",
      "npm:redux-devtools-themes@1.0.0",
      "npm:redux-devtools-log-monitor@1.0.4/lib/reducers",
      "npm:redux-devtools-log-monitor@1.0.4/lib/LogMonitorEntry",
      "npm:redux-devtools-log-monitor@1.0.4/lib/LogMonitorButton",
      "npm:react-pure-render@1.0.2/shallowEqual",
      "npm:redux-devtools-log-monitor@1.0.4/lib/brighten",
      "npm:react-json-tree@0.5.1",
      "npm:redux-devtools-themes@1.0.0/lib/index",
      "npm:redux-devtools-log-monitor@1.0.4/lib/LogMonitorEntryAction",
      "npm:react-json-tree@0.5.1/lib/index",
      "npm:base16@1.0.0",
      "npm:redux-devtools-themes@1.0.0/lib/nicinabox",
      "npm:react-json-tree@0.5.1/lib/grab-node",
      "npm:react-json-tree@0.5.1/lib/themes/solarized",
      "npm:base16@1.0.0/lib/index",
      "npm:react-json-tree@0.5.1/lib/obj-type",
      "npm:react-json-tree@0.5.1/lib/JSONObjectNode",
      "npm:react-json-tree@0.5.1/lib/JSONValueNode",
      "npm:react-json-tree@0.5.1/lib/JSONIterableNode",
      "npm:react-json-tree@0.5.1/lib/JSONArrayNode",
      "npm:base16@1.0.0/lib/threezerotwofour",
      "npm:base16@1.0.0/lib/ashes",
      "npm:base16@1.0.0/lib/atelier-dune",
      "npm:base16@1.0.0/lib/atelier-forest",
      "npm:base16@1.0.0/lib/apathy",
      "npm:base16@1.0.0/lib/atelier-heath",
      "npm:base16@1.0.0/lib/atelier-lakeside",
      "npm:base16@1.0.0/lib/bespin",
      "npm:base16@1.0.0/lib/atelier-seaside",
      "npm:base16@1.0.0/lib/brewer",
      "npm:base16@1.0.0/lib/bright",
      "npm:base16@1.0.0/lib/chalk",
      "npm:base16@1.0.0/lib/codeschool",
      "npm:base16@1.0.0/lib/default",
      "npm:base16@1.0.0/lib/colors",
      "npm:base16@1.0.0/lib/eighties",
      "npm:base16@1.0.0/lib/embers",
      "npm:base16@1.0.0/lib/google",
      "npm:base16@1.0.0/lib/flat",
      "npm:base16@1.0.0/lib/grayscale",
      "npm:base16@1.0.0/lib/greenscreen",
      "npm:base16@1.0.0/lib/harmonic",
      "npm:base16@1.0.0/lib/hopscotch",
      "npm:base16@1.0.0/lib/isotope",
      "npm:base16@1.0.0/lib/mocha",
      "npm:base16@1.0.0/lib/marrakesh",
      "npm:base16@1.0.0/lib/monokai",
      "npm:base16@1.0.0/lib/ocean",
      "npm:base16@1.0.0/lib/paraiso",
      "npm:base16@1.0.0/lib/railscasts",
      "npm:base16@1.0.0/lib/shapeshifter",
      "npm:base16@1.0.0/lib/pop",
      "npm:base16@1.0.0/lib/solarized",
      "npm:base16@1.0.0/lib/summerfruit",
      "npm:base16@1.0.0/lib/tube",
      "npm:base16@1.0.0/lib/tomorrow",
      "npm:base16@1.0.0/lib/twilight",
      "npm:react-json-tree@0.5.1/lib/utils/hexToRgb",
      "npm:react-json-tree@0.5.1/lib/mixins/index",
      "npm:react-json-tree@0.5.1/lib/JSONNestedNode",
      "npm:react-mixin@1.7.0",
      "npm:react-json-tree@0.5.1/lib/mixins/squash-click-event",
      "npm:react-json-tree@0.5.1/lib/mixins/expanded-state-handler",
      "npm:react-json-tree@0.5.1/lib/JSONArrow",
      "npm:react-mixin@1.7.0/index",
      "npm:object-assign@2.1.1",
      "npm:smart-mixin@1.2.1",
      "npm:object-assign@2.1.1/index",
      "npm:smart-mixin@1.2.1/index",
      "npm:redux-devtools-dock-monitor@1.0.1",
      "npm:redux-devtools-dock-monitor@1.0.1/lib/index",
      "npm:redux-devtools-dock-monitor@1.0.1/lib/DockMonitor",
      "npm:redux-devtools-dock-monitor@1.0.1/lib/constants",
      "npm:redux-devtools-dock-monitor@1.0.1/lib/actions",
      "npm:react-dock@0.2.3",
      "npm:redux-devtools-dock-monitor@1.0.1/lib/reducers",
      "npm:parse-key@0.2.1",
      "npm:react-dock@0.2.3/lib/index",
      "npm:parse-key@0.2.1/parse-key",
      "npm:babel-runtime@5.8.35/helpers/interop-require-default",
      "npm:react-dock@0.2.3/lib/Dock",
      "npm:parse-key@0.2.1/keycodes",
      "npm:babel-runtime@5.8.35/helpers/class-call-check",
      "npm:babel-runtime@5.8.35/helpers/get",
      "npm:babel-runtime@5.8.35/helpers/inherits",
      "npm:babel-runtime@5.8.35/helpers/create-class",
      "npm:babel-runtime@5.8.35/helpers/extends",
      "npm:babel-runtime@5.8.35/helpers/to-consumable-array",
      "npm:lodash.debounce@3.1.1",
      "npm:babel-runtime@5.8.35/core-js/object/keys",
      "npm:object-assign@4.0.1",
      "npm:react-dock@0.2.3/lib/autoprefix",
      "npm:babel-runtime@5.8.35/core-js/object/get-own-property-descriptor",
      "npm:babel-runtime@5.8.35/core-js/object/create",
      "npm:babel-runtime@5.8.35/core-js/object/assign",
      "npm:babel-runtime@5.8.35/core-js/object/set-prototype-of",
      "npm:babel-runtime@5.8.35/core-js/object/define-property",
      "npm:babel-runtime@5.8.35/core-js/array/from",
      "npm:core-js@1.2.6/library/fn/object/keys",
      "npm:lodash.debounce@3.1.1/index",
      "npm:object-assign@4.0.1/index",
      "npm:core-js@1.2.6/library/fn/object/assign",
      "npm:core-js@1.2.6/library/fn/array/from",
      "npm:core-js@1.2.6/library/fn/object/set-prototype-of",
      "npm:core-js@1.2.6/library/fn/object/define-property",
      "npm:core-js@1.2.6/library/fn/object/get-own-property-descriptor",
      "npm:core-js@1.2.6/library/modules/$.core",
      "npm:core-js@1.2.6/library/fn/object/create",
      "npm:core-js@1.2.6/library/modules/es6.object.keys",
      "npm:lodash._getnative@3.9.1",
      "npm:core-js@1.2.6/library/modules/$",
      "npm:core-js@1.2.6/library/modules/es6.array.from",
      "npm:core-js@1.2.6/library/modules/es6.object.set-prototype-of",
      "npm:core-js@1.2.6/library/modules/es6.object.get-own-property-descriptor",
      "npm:core-js@1.2.6/library/modules/es6.string.iterator",
      "npm:core-js@1.2.6/library/modules/es6.object.assign",
      "npm:core-js@1.2.6/library/modules/$.to-object",
      "npm:core-js@1.2.6/library/modules/$.object-sap",
      "npm:lodash._getnative@3.9.1/index",
      "npm:core-js@1.2.6/library/modules/$.ctx",
      "npm:core-js@1.2.6/library/modules/$.iter-call",
      "npm:core-js@1.2.6/library/modules/$.export",
      "npm:core-js@1.2.6/library/modules/$.is-array-iter",
      "npm:core-js@1.2.6/library/modules/$.to-length",
      "npm:core-js@1.2.6/library/modules/core.get-iterator-method",
      "npm:core-js@1.2.6/library/modules/$.to-iobject",
      "npm:core-js@1.2.6/library/modules/$.string-at",
      "npm:core-js@1.2.6/library/modules/$.iter-define",
      "npm:core-js@1.2.6/library/modules/$.iter-detect",
      "npm:core-js@1.2.6/library/modules/$.set-proto",
      "npm:core-js@1.2.6/library/modules/$.defined",
      "npm:core-js@1.2.6/library/modules/$.fails",
      "npm:core-js@1.2.6/library/modules/$.object-assign",
      "npm:core-js@1.2.6/library/modules/$.a-function",
      "npm:core-js@1.2.6/library/modules/$.global",
      "npm:core-js@1.2.6/library/modules/$.iterators",
      "npm:core-js@1.2.6/library/modules/$.to-integer",
      "npm:core-js@1.2.6/library/modules/$.library",
      "npm:core-js@1.2.6/library/modules/$.has",
      "npm:core-js@1.2.6/library/modules/$.an-object",
      "npm:core-js@1.2.6/library/modules/$.wks",
      "npm:core-js@1.2.6/library/modules/$.classof",
      "npm:core-js@1.2.6/library/modules/$.redefine",
      "npm:core-js@1.2.6/library/modules/$.iobject",
      "npm:core-js@1.2.6/library/modules/$.hide",
      "npm:core-js@1.2.6/library/modules/$.iter-create",
      "npm:core-js@1.2.6/library/modules/$.is-object",
      "npm:core-js@1.2.6/library/modules/$.set-to-string-tag",
      "npm:core-js@1.2.6/library/modules/$.cof",
      "npm:core-js@1.2.6/library/modules/$.uid",
      "npm:core-js@1.2.6/library/modules/$.shared",
      "npm:core-js@1.2.6/library/modules/$.descriptors",
      "npm:core-js@1.2.6/library/modules/$.property-desc",
      "npm:history@2.0.0",
      "npm:history@2.0.0/lib/index",
      "npm:history@2.0.0/lib/createBrowserHistory",
      "npm:history@2.0.0/lib/Actions",
      "npm:history@2.0.0/lib/enableBeforeUnload",
      "npm:history@2.0.0/lib/enableQueries",
      "npm:history@2.0.0/lib/createMemoryHistory",
      "npm:history@2.0.0/lib/createHashHistory",
      "npm:history@2.0.0/lib/deprecate",
      "npm:history@2.0.0/lib/createLocation",
      "npm:warning@2.1.0",
      "npm:warning@2.1.0/browser",
      "npm:history@2.0.0/lib/useBasename",
      "npm:history@2.0.0/lib/useBeforeUnload",
      "npm:history@2.0.0/lib/useQueries",
      "npm:query-string@3.0.0",
      "npm:query-string@3.0.0/index",
      "npm:strict-uri-encode@1.1.0",
      "npm:strict-uri-encode@1.1.0/index",
      "npm:history@2.0.0/lib/ExecutionEnvironment",
      "npm:history@2.0.0/lib/DOMUtils",
      "npm:history@2.0.0/lib/DOMStateStorage",
      "npm:history@2.0.0/lib/createDOMHistory",
      "npm:history@2.0.0/lib/PathUtils",
      "npm:history@2.0.0/lib/createHistory",
      "npm:deep-equal@1.0.1",
      "npm:deep-equal@1.0.1/index",
      "npm:deep-equal@1.0.1/lib/keys",
      "npm:deep-equal@1.0.1/lib/is_arguments",
      "npm:history@2.0.0/lib/runTransitionHook",
      "npm:history@2.0.0/lib/AsyncUtils",
      "npm:react-router@1.0.3",
      "npm:react-router@1.0.3/lib/index",
      "npm:react-router@1.0.3/lib/Link",
      "npm:react-router@1.0.3/lib/RouteContext",
      "npm:react-router@1.0.3/lib/IndexLink",
      "npm:react-router@1.0.3/lib/History",
      "npm:react-router@1.0.3/lib/IndexRedirect",
      "npm:react-router@1.0.3/lib/Redirect",
      "npm:react-router@1.0.3/lib/IndexRoute",
      "npm:react-router@1.0.3/lib/Lifecycle",
      "npm:react-router@1.0.3/lib/Router",
      "npm:react-router@1.0.3/lib/PropTypes",
      "npm:react-router@1.0.3/lib/Route",
      "npm:react-router@1.0.3/lib/RouteUtils",
      "npm:react-router@1.0.3/lib/RoutingContext",
      "npm:react-router@1.0.3/lib/useRoutes",
      "npm:react-router@1.0.3/lib/match",
      "npm:react-router@1.0.3/lib/PatternUtils",
      "npm:history@1.17.0/lib/createHashHistory",
      "npm:history@1.17.0/lib/Actions",
      "npm:react-router@1.0.3/lib/getRouteParams",
      "npm:react-router@1.0.3/lib/computeChangedRoutes",
      "npm:react-router@1.0.3/lib/TransitionUtils",
      "npm:react-router@1.0.3/lib/getComponents",
      "npm:react-router@1.0.3/lib/isActive",
      "npm:history@1.17.0/lib/useQueries",
      "npm:react-router@1.0.3/lib/matchRoutes",
      "npm:history@1.17.0/lib/useBasename",
      "npm:history@1.17.0/lib/createMemoryHistory",
      "npm:history@1.17.0/lib/DOMUtils",
      "npm:history@1.17.0/lib/ExecutionEnvironment",
      "npm:history@1.17.0/lib/createDOMHistory",
      "npm:history@1.17.0/lib/parsePath",
      "npm:react-router@1.0.3/lib/AsyncUtils",
      "npm:history@1.17.0/lib/DOMStateStorage",
      "npm:history@1.17.0/lib/deprecate",
      "npm:history@1.17.0/lib/runTransitionHook",
      "npm:history@1.17.0/lib/extractPath",
      "npm:history@1.17.0/lib/createHistory",
      "npm:history@1.17.0/lib/AsyncUtils",
      "npm:history@1.17.0/lib/createLocation",
      "npm:react-dom@0.14.7",
      "npm:react-dom@0.14.7/index"
    ]
  },

  map: {
    "axios": "npm:axios@0.9.1",
    "babel": "npm:babel-core@5.8.35",
    "babel-runtime": "npm:babel-runtime@5.8.35",
    "core-js": "npm:core-js@1.2.6",
    "history": "npm:history@2.0.0",
    "react": "npm:react@0.14.7",
    "react-dom": "npm:react-dom@0.14.7",
    "react-redux": "npm:react-redux@4.4.0",
    "react-router": "npm:react-router@1.0.3",
    "redux": "npm:redux@3.3.0",
    "redux-devtools": "npm:redux-devtools@3.1.0",
    "redux-devtools-dock-monitor": "npm:redux-devtools-dock-monitor@1.0.1",
    "redux-devtools-log-monitor": "npm:redux-devtools-log-monitor@1.0.4",
    "redux-thunk": "npm:redux-thunk@1.0.3",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.11.0"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-https@0.1.0": {
      "https-browserify": "npm:https-browserify@0.0.0"
    },
    "github:jspm/nodelibs-net@0.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "net": "github:jspm/nodelibs-net@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "timers": "github:jspm/nodelibs-timers@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-timers@0.1.0": {
      "timers-browserify": "npm:timers-browserify@1.4.2"
    },
    "github:jspm/nodelibs-tty@0.1.0": {
      "tty-browserify": "npm:tty-browserify@0.0.0"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "github:jspm/nodelibs-zlib@0.1.0": {
      "browserify-zlib": "npm:browserify-zlib@0.1.4"
    },
    "npm:asn1.js@4.4.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "bn.js": "npm:bn.js@4.10.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:axios@0.9.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "follow-redirects": "npm:follow-redirects@0.0.7",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "zlib": "github:jspm/nodelibs-zlib@0.1.0"
    },
    "npm:babel-runtime@5.8.35": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:babel-runtime@6.3.19": {
      "core-js": "npm:core-js@1.2.6",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:bn.js@4.10.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:browserify-aes@1.0.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-xor": "npm:buffer-xor@1.0.3",
      "cipher-base": "npm:cipher-base@1.0.2",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:browserify-cipher@1.0.0": {
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "browserify-des": "npm:browserify-des@1.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0"
    },
    "npm:browserify-des@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "des.js": "npm:des.js@1.0.0",
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:browserify-rsa@4.0.0": {
      "bn.js": "npm:bn.js@4.10.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.2"
    },
    "npm:browserify-sign@4.0.0": {
      "bn.js": "npm:bn.js@4.10.1",
      "browserify-rsa": "npm:browserify-rsa@4.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.2.3",
      "inherits": "npm:inherits@2.0.1",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:browserify-zlib@0.1.4": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "pako": "npm:pako@0.2.8",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "readable-stream": "npm:readable-stream@2.0.5",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:buffer-xor@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:cipher-base@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-js@1.2.6": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:create-ecdh@4.0.0": {
      "bn.js": "npm:bn.js@4.10.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.2.3"
    },
    "npm:create-hash@1.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "ripemd160": "npm:ripemd160@1.0.1",
      "sha.js": "npm:sha.js@2.4.4"
    },
    "npm:create-hmac@1.1.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:crypto-browserify@3.11.0": {
      "browserify-cipher": "npm:browserify-cipher@1.0.0",
      "browserify-sign": "npm:browserify-sign@4.0.0",
      "create-ecdh": "npm:create-ecdh@4.0.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "diffie-hellman": "npm:diffie-hellman@5.0.2",
      "inherits": "npm:inherits@2.0.1",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "public-encrypt": "npm:public-encrypt@4.0.0",
      "randombytes": "npm:randombytes@2.0.2"
    },
    "npm:debug@2.2.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ms": "npm:ms@0.7.1",
      "net": "github:jspm/nodelibs-net@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "tty": "github:jspm/nodelibs-tty@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:des.js@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
    },
    "npm:diffie-hellman@5.0.2": {
      "bn.js": "npm:bn.js@4.10.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@4.0.0",
      "randombytes": "npm:randombytes@2.0.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:elliptic@6.2.3": {
      "bn.js": "npm:bn.js@4.10.1",
      "brorand": "npm:brorand@1.0.5",
      "hash.js": "npm:hash.js@1.0.3",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:evp_bytestokey@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:fbjs@0.6.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:follow-redirects@0.0.7": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "debug": "npm:debug@2.2.0",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-consume": "npm:stream-consume@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0"
    },
    "npm:hash.js@1.0.3": {
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:history@1.17.0": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "deep-equal": "npm:deep-equal@1.0.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "invariant": "npm:invariant@2.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "query-string": "npm:query-string@3.0.0",
      "warning": "npm:warning@2.1.0"
    },
    "npm:history@2.0.0": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "deep-equal": "npm:deep-equal@1.0.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "invariant": "npm:invariant@2.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "query-string": "npm:query-string@3.0.0",
      "warning": "npm:warning@2.1.0"
    },
    "npm:https-browserify@0.0.0": {
      "http": "github:jspm/nodelibs-http@1.7.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:invariant@2.2.0": {
      "loose-envify": "npm:loose-envify@1.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:isarray@1.0.0": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:lodash.debounce@3.1.1": {
      "lodash._getnative": "npm:lodash._getnative@3.9.1"
    },
    "npm:lodash@4.2.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:loose-envify@1.1.0": {
      "js-tokens": "npm:js-tokens@1.0.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:miller-rabin@4.0.0": {
      "bn.js": "npm:bn.js@4.10.1",
      "brorand": "npm:brorand@1.0.5"
    },
    "npm:pako@0.2.8": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:parse-asn1@5.0.0": {
      "asn1.js": "npm:asn1.js@4.4.0",
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:pbkdf2@3.0.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:process-nextick-args@1.0.6": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:public-encrypt@4.0.0": {
      "bn.js": "npm:bn.js@4.10.1",
      "browserify-rsa": "npm:browserify-rsa@4.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "randombytes": "npm:randombytes@2.0.2"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:query-string@3.0.0": {
      "strict-uri-encode": "npm:strict-uri-encode@1.1.0"
    },
    "npm:randombytes@2.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:react-dock@0.2.3": {
      "lodash.debounce": "npm:lodash.debounce@3.1.1",
      "object-assign": "npm:object-assign@4.0.1",
      "react": "npm:react@0.14.7"
    },
    "npm:react-dom@0.14.7": {
      "react": "npm:react@0.14.7"
    },
    "npm:react-json-tree@0.5.1": {
      "babel-runtime": "npm:babel-runtime@6.3.19",
      "react": "npm:react@0.14.7",
      "react-mixin": "npm:react-mixin@1.7.0"
    },
    "npm:react-mixin@1.7.0": {
      "object-assign": "npm:object-assign@2.1.1",
      "smart-mixin": "npm:smart-mixin@1.2.1"
    },
    "npm:react-redux@4.4.0": {
      "hoist-non-react-statics": "npm:hoist-non-react-statics@1.0.5",
      "invariant": "npm:invariant@2.2.0",
      "lodash": "npm:lodash@4.2.1",
      "loose-envify": "npm:loose-envify@1.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@0.14.7",
      "redux": "npm:redux@3.3.0"
    },
    "npm:react-router@1.0.3": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "history": "npm:history@1.17.0",
      "invariant": "npm:invariant@2.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "warning": "npm:warning@2.1.0"
    },
    "npm:react@0.14.7": {
      "fbjs": "npm:fbjs@0.6.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.13": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:readable-stream@2.0.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "process-nextick-args": "npm:process-nextick-args@1.0.6",
      "string_decoder": "npm:string_decoder@0.10.31",
      "util-deprecate": "npm:util-deprecate@1.0.2"
    },
    "npm:redux-devtools-dock-monitor@1.0.1": {
      "babel-runtime": "npm:babel-runtime@6.3.19",
      "parse-key": "npm:parse-key@0.2.1",
      "react": "npm:react@0.14.7",
      "react-dock": "npm:react-dock@0.2.3",
      "react-pure-render": "npm:react-pure-render@1.0.2",
      "redux-devtools": "npm:redux-devtools@3.1.0"
    },
    "npm:redux-devtools-log-monitor@1.0.4": {
      "react": "npm:react@0.14.7",
      "react-json-tree": "npm:react-json-tree@0.5.1",
      "react-pure-render": "npm:react-pure-render@1.0.2",
      "redux-devtools": "npm:redux-devtools@3.1.0",
      "redux-devtools-themes": "npm:redux-devtools-themes@1.0.0"
    },
    "npm:redux-devtools-themes@1.0.0": {
      "base16": "npm:base16@1.0.0"
    },
    "npm:redux-devtools@3.1.0": {
      "lodash": "npm:lodash@4.2.1",
      "react": "npm:react@0.14.7",
      "react-redux": "npm:react-redux@4.4.0",
      "redux": "npm:redux@3.3.0"
    },
    "npm:redux@3.3.0": {
      "lodash": "npm:lodash@4.2.1",
      "loose-envify": "npm:loose-envify@1.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:ripemd160@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:sha.js@2.4.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:smart-mixin@1.2.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.13"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:timers-browserify@1.4.2": {
      "process": "npm:process@0.11.2"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util-deprecate@1.0.2": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:warning@2.1.0": {
      "loose-envify": "npm:loose-envify@1.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
